site_name: OceanHackWeek'20 Resources
repo_url: https://github.com/oceanhackweek/ohw-resources

nav:
  - Overview: index.md
  - Code of Conduct: conduct.md
  - Logistics: 
    - logistics/overview.md
    - schedule.md
    - Getting Help: logistics/getting_help.md
  - Pre-event Preparation:
    - Git: prep/git.md
    - GitHub: prep/github.md
    - Jupyter and the Hub: prep/jupyterhub.md
    # - Conda, Python, R: prep/conda.md
    # - Python Requirements: preweek/python.md
    # - Numpy: numpy.md
    # - Pandas: pandas.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    # - Data Access in Python: tutorials/github.md
  - Projects: 
    - Project Overview: projects/overview.md
    - Hacking at OHW20: projects/steps.md

theme: 
  name: readthedocs
  collapse_by_default: false
  highlightjs: true

plugins:
  - search
  - markdownextradata

markdown_extensions:
  - admonition

extra_css:
  - extra.css

extra:
  hackweek:
    name: OceanHackWeek
    web_url: https://oceanhackweek.github.io/ohw-resources
    slack_url: https://oceanhackweek.slack.com
    github_org_url: https://github.com/oceanhackweek/
    jupyterhub_url: https://ocean.hackweek.io
    email: oceanhkw@uw.edu
    admin_contact: Emilio Mayorga

